name: Download Repository

on:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download zip
        run: |
          curl -LO (link unavailable) --output TermuxRoot-Script.zip 
